// Code generated by mockery v1.0.0. DO NOT EDIT.

package group

import mock "github.com/stretchr/testify/mock"

// MockWriter is an autogenerated mock type for the Writer type
type MockWriter struct {
	mock.Mock
}
