// Code generated by mockery v1.0.0. DO NOT EDIT.

package alert

import (
	context "context"

	inovibe_api_v3 "bitbucket.org/ino-on/ino-vibe-api"
	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *MockClient) Close() {
	_m.Called()
}

// List provides a mock function with given fields: ctx, request
func (_m *MockClient) List(ctx context.Context, request *inovibe_api_v3.AlertListRequest) (*inovibe_api_v3.AlertListResponse, error) {
	ret := _m.Called(ctx, request)

	var r0 *inovibe_api_v3.AlertListResponse
	if rf, ok := ret.Get(0).(func(context.Context, *inovibe_api_v3.AlertListRequest) *inovibe_api_v3.AlertListResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*inovibe_api_v3.AlertListResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *inovibe_api_v3.AlertListRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
