// Code generated by mockery v1.0.0. DO NOT EDIT.

package user

import mock "github.com/stretchr/testify/mock"

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

// RegisterDeviceToken provides a mock function with given fields: userID, username, deviceToken
func (_m *MockClient) RegisterDeviceToken(userID string, username string, deviceToken string) error {
	ret := _m.Called(userID, username, deviceToken)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(userID, username, deviceToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
